name: mlagents
channels:
- pytorch
- conda-forge
dependencies:
- jupyterlab
- matplotlib
- numpy[version='<2.0']
- python=3.9
- pytorch::pytorch
- tensorflow
- pandas 
- scipy
- pip
- pip:
  - mlagents
  - protobuf==3.20
  - ./Value-based-methods/python
